### ISSUE TITLE
Tên tài khoản facebook ở phần comment có dấu "}" cuối phần tên

### ISSUE THREAD

**Issue by golddessun** [sontrinh/search-redditvn-react#2]
![image](https://user-images.githubusercontent.com/2587351/33971407-47e4503c-e046-11e7-8e56-01aead888811.png)

**Comment by tdtgit** [comment]
#1 Tui có tạo PR rồi, đợi bên đó merge vào hoi.

**Comment by polepoe** [comment]
Okay để tối bạn OP review rồi mình setup lại CI CD cho project luôn xD, cám ơn các bạn.
