### ISSUE TITLE
Nên tạo 1 trang 404 thực thụ và ẩn post_id đi

### ISSUE THREAD

**Issue by golddessun** [sontrinh/search-redditvn-react#4]
![image](https://user-images.githubusercontent.com/2587351/33971779-3dff30c6-e048-11e7-9246-96b26f60a734.png)

Mình để nghị được thì nên thay khung code màu đỏ bằng 1 cái hình logo 404 như thế này
![image](https://user-images.githubusercontent.com/2587351/33971799-537e3b86-e048-11e7-85e4-2419660a1108.png)

**Comment by messenger2011** [comment]
Việt hóa 404 luôn đi @sontrinh
